### ISSUE TITLE
[Question] Is there any way to change the animation?

### ISSUE THREAD

**Issue by BlierNicolas** [stephane-monnot/react-vertical-timeline#12]
Hi,

First of all, very good job for the timeline! (if you want to see it what I did with it https://www.venatusuniverse.com/en/events)

But just a small question, is there any way to change the animation? I want to make the bubble to come from the bottom of the page instead of the right side of the page.

Thanks in advance,

Nico

**Comment by stephane-monnot** [comment]
Hi,
I fixed animation on desktop in the last version : 2.1.3.
If you want to change animation, you can use css :
```css
.vertical-timeline--animate .vertical-timeline-element-content.bounce-in {
  visibility: visible;
  animation: custom-animation 0.6s !important;
}
@keyframes custom-animation {
  0% {
    opacity: 0;
    transform: scale(0);
  }
  60% {
    opacity: 1;
    transform: scale(1.1);
  }
  100% {
    transform: scale(1);
  }
}
```
