### ISSUE TITLE
How to change border color of element?

### ISSUE THREAD

**Issue by vmkgalvatron** [stephane-monnot/react-vertical-timeline#130]

**Comment by michaelbrusegard** [comment]
Add this CSS class to the icon and replace #FF0000 with the colour of your choice.

```css
.border-color {
    box-shadow: 0 0 0 4px #FF0000;
    border-radius: 50%;
}
```
