### ISSUE TITLE
Change style.css

### ISSUE THREAD

**Issue by kaansancak** [stephane-monnot/react-vertical-timeline#33]
Is there anyway to modify the line color of the timeline ?

**Comment by stephane-monnot** [comment]
```css
.vertical-timeline::before {
    background: black;
}

.vertical-timeline-element-icon {
    box-shadow: 0 0 0 4px black, inset 0 2px 0 rgba(0, 0, 0, 0.08), 0 3px 0 4px rgba(0, 0, 0, 0.05);
}
```
