### ISSUE TITLE
Can we make the date time on the left side of line

### ISSUE THREAD

**Issue by ShuhaoWang-AI** [stephane-monnot/react-vertical-timeline#34]
Can we make the date time on the left side of line

**Comment by stephane-monnot** [comment]
With some css, yes. 
For example, you can update position of `.vertical-timeline-element-date` : 
```css
.vertical-timeline--two-columns .vertical-timeline-element-content .vertical-timeline-element-date {
    position: initial;
}
```
