### ISSUE TITLE
Question on Date location

### ISSUE THREAD

**Issue by msalimbe1** [stephane-monnot/react-vertical-timeline#46]
If I choose the 1-column layout, the date is automatically placed at the bottom of the tile. I would like to place it on the left of the Icon. Just like it does for the 2-column layout. Is this possible?

Thanks!

**Comment by stephane-monnot** [comment]
It's possible with some css rules : 
```css
@media only screen and (min-width: 768px)
.vertical-timeline-element-content .vertical-timeline-element-date {
    font-size: 0.875rem;
    position: absolute;
    width: 100%;
    top: -2px;
    left: auto;
    right: 109%;
    text-align: right;
}
```
![image](https://user-images.githubusercontent.com/6066368/72436388-a2673c80-37e3-11ea-8181-3b89223570f6.png)
