### ISSUE TITLE
CSS border-image doesn't work

### ISSUE THREAD

**Issue by ultimagriever** [stephane-monnot/react-vertical-timeline#5]
When I try to set a `border-image` CSS value to `.vertical-timeline-element-content`, I only get tiny squares at the corners of the balloon instead of getting a full border. I'm attempting to set the border as a gradient (using `linear-gradient`), while setting `border` works fine.

### SCSS
```sass
.vertical-timeline-element {
  .vertical-timeline-element-content {
    border: 10px 0 0 0;
    border-image: linear-gradient(to right, #FF0000, #000000);
  }
}
```

**Comment by stephane-monnot** [comment]
I tried your code sample, if I change `border: 10px 0 0 0;` to `border: 10px solid transparent;`, and add `border-image-slice: 1;`, I get : 
![image](https://user-images.githubusercontent.com/6066368/37763386-2fc6151e-2dbf-11e8-89e8-d9e451b2d7e5.png)

But I think you want to create a border inside, right ? If so, I recommend you to create a div (wrapper) inside the `vertical-timeline-element-content` element and remove the padding of `.vertical-timeline-element-content`.
![image](https://user-images.githubusercontent.com/6066368/37764641-78ed2054-2dc2-11e8-8dfd-13ad8193d254.png)
```jsx
<VerticalTimelineElement
  className="vertical-timeline-element--work"
  date="2011 - present"
  iconStyle={{ background: 'rgb(33, 150, 243)', color: '#fff' }}
  icon={<WorkIcon />}
>
  <div className="vertical-timeline-element-content-box">
    <h3 className="vertical-timeline-element-title">Creative Director</h3>
    <h4 className="vertical-timeline-element-subtitle">Miami, FL</h4>
    <p>
      Creative Direction, User Experience, Visual Design, Project Management, Team Leading
    </p>
  </div>
</VerticalTimelineElement>
```
```scss
.vertical-timeline-element {
  .vertical-timeline-element-content-box {
    padding: 1em;
    border-radius: 0.25em;
    border: 4px solid transparent;
    border-image: linear-gradient(to right, #000000, #0098ED);
    border-image-slice: 1;
  }

  .vertical-timeline-element-content::before {
    border-left-color: #0098ED;
  }

  @media only screen and (min-width: 1170px) {
    .vertical-timeline-element-content .vertical-timeline-element-date {
      left: 136%;
    }

    &:nth-child(even):not(.vertical-timeline-element--left) .vertical-timeline-element-content .vertical-timeline-element-date, .vertical-timeline-element.vertical-timeline-element--right .vertical-timeline-element-content .vertical-timeline-element-date {
      right: 136% !important;
    }
  }
}
```
